class Specification:
  CONV_NAME = ['conversion_1',
               'conversion_2',
               'conversion_3',
               'conversion_4',
               'conversion_5',
               'conversion_6',
               'conversion_7',
               'conversion_8',
               'conversion_9',
               'conversion_10',
               'conversion_11',
               'conversion_12',
               'conversion_13',
               'conversion_14',
               'conversion_15',
               'conversion_16',
               'conversion_17',
               'conversion_18',
               'conversion_19',
               'conversion_20',
               'conversion_21',
               'conversion_22',
               'conversion_23',
               'conversion_24',
               'conversion_25',
               'conversion_26',
               'conversion_27',
               'conversion_28',
               'conversion_29',
               'conversion_30',
               'conversion_31',
               'conversion_32',
               'conversion_33',
               'conversion_34',
               'conversion_35',
               'conversion_36',
               'conversion_37',
               'conversion_38',
               'conversion_39',
               'conversion_40',
               'conversion_41',
               'conversion_42',
               'conversion_43',
               'conversion_44',
               'conversion_45',
               'conversion_46',
               'conversion_47',
               'conversion_48',
               'conversion_49',
               'conversion_50',
               'conversion_51',
               'conversion_52',
               'conversion_53',
               'conversion_54',
               'conversion_55',
               'conversion_56',
               'conversion_57',
               'conversion_58',
               'conversion_59',
               'conversion_60',
               'conversion_61',
               'conversion_62',
               'conversion_63',
               'conversion_64',
               'conversion_65',
               'conversion_66',
               'conversion_67',
               'conversion_68',
               'conversion_69',
               'conversion_70',
               'conversion_71',
               'conversion_72',
               'conversion_73',
               'conversion_74',
               'conversion_75',
               'conversion_76',
               'conversion_77',
               'conversion_78',
               'conversion_79',
               'conversion_80',
               'conversion_81',
               'conversion_82',
               'conversion_83',
               'conversion_84',
               'conversion_85',
               'conversion_86',
               'conversion_87',
               'conversion_88',
               'conversion_89',
               'conversion_90',
               'conversion_91',
               'conversion_92',
               'conversion_93',
               'conversion_94',
               'conversion_95',
               'conversion_96',
               'conversion_97',
               'conversion_98',
               'conversion_99',
               'conversion_100',
               'conversion_101',
               'conversion_102',
               'conversion_103',
               'conversion_104',
               'conversion_105',
               'conversion_106',
               'conversion_107',
               'conversion_108']
  SPECS = [[{'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'infoPages'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'none'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'thankYouPage'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType1',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType1',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType1',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'allPages'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'signUpPages'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'homepage'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType2',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'download'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType2',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType2',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'allPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'landingPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'landingPages'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'infoPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'signUpPages'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'none'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'none'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'homepage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'productPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'productPage'}}],
   [{'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'thankYouPage'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'all',
               'conversionType': 'conversionType3',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'postImpression',
               'conversionType': 'conversionType3',
               'pageCategory': 'download'}},
    {'metric': 'conversions',
     'specs': {'adInteraction': 'recentClick',
               'conversionType': 'conversionType3',
               'pageCategory': 'download'}}]]
